RSSapp/urls.py
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'RSSapp'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('', views.Index, name='index'),
    path('results', views.Results, name='results')
]

RSSproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RSSapp.urls'))
]

RSSpython/urls.py
import json

### list of urls to start with for json file
RSS_URLS = [
    "https://medium.com/feed/topic/artificial-intelligence",
    "https://stackoverflow.com/feeds",
    "https://www.djangoproject.com/rss/weblog/",
    "https://nu.nl/rss",
    "https://medium.com/feed/topic/machine-learning",
    ]
f = open("urls.json","w", encoding="utf-8")
json = json.dumps(RSS_URLS, ensure_ascii=False)
f.write(json)
f.close()

RSSapp/models.py
from django.db import models
import datetime

# Create your models here.

class RSS_URLS(models.Model):
    url = models.URLField(unique=True)
    # title = models.CharField(max_length=128)

    def get_absolute_url(self):
        return reverse('goal_app:rss_urls')

class Feed(models.Model):
    url = models.ForeignKey(RSS_URLS, on_delete=models.CASCADE)
    title = models.CharField(max_length=128, blank=True)
    summary = models.CharField(max_length=500, blank=True)
    published = models.DateField(null=True, blank=True)
    updated = models.DateField(null=True, blank=True)
    imported = models.DateField(default=datetime.date.today)

RSSapp/forms.py
from django import forms
from .models import RSS_URLS, Feed

class InputURLS(forms.Form):
    url1 = forms.URLField()
    url2 = forms.URLField(required=False)
    url3 = forms.URLField(required=False)

    def __init__(self, *args, **kwargs):
        super(InputURLS, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    # def clean(self):
    #     cleaned_data = super(InputURLS, self).clean()
    #     url1 = cleaned_data.get('url1')
    #     url2 = cleaned_data.get('url2')
    #     url3 = cleaned_data.get('url3')
    #     if not url1 or not url2 or not url3:
    #         raise forms.ValidationError('You have to choose or input something!')

# class SelectURLS(forms.ModelForm):
#     class Meta:
#         model = RSS_URLS
#         fields= ('url',)
#
#     def __init__(self, *args, **kwargs):
#         super(SelectURLS, self).__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs.update({'class': 'form-control'})

RSSapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
import datetime
from .models import RSS_URLS
from .forms import InputURLS
import feedparser


# Create your views here.
def Index(request):
    now = datetime.datetime.now()
    str_now = now.strftime("%d %B, %Y")

    if request.method == 'POST':
        url1 = request.POST['url1']
        url2 = request.POST['url2']
        url3 = request.POST['url3']
        urls = [url1, url2, url3]
        titles = []
        feeds = []
        for url in urls:
            if not url:
                pass
            else:
                if 'www' in url:
                    i1 = url.find('.')
                    i2 = url.find('.', (i1+1))
                    titles.append(url[(i1+1):i2])
                else:
                    i1 = 2 + url.find('/')
                    i2 = url.find('.')
                    titles.append(url[i1:i2])
                if feedparser.parse(url):
                    feeds.append(feedparser.parse(url))
                else:
                    feeds.append("No RSS feeds found for the given url")

        context = {"titles": titles, "feeds": feeds, "date": str_now}
        return render(request, 'results.html', context)

    else:
        form = InputURLS()
        context = {"form": form,"date": str_now}
        return render(request, 'index.html', context)


def Results(request):
    return render(request, 'results.html')

RSSapp/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai+2:400,600,700&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css?family=Bitter:400,700&display=swap" rel="stylesheet"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'RSS.ico' %}">

    <title>
      {% block title_block %}

      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container-fluid h-100">

      <div class="row h-100">
        <div class="col">

          <div class="row align-items-center" id="banner">
            <!-- Promo header -->
            <div class="col text-center" id="promo">
              <h1 id="title" class="mb-2">RSS feed assignment</h1>
            </div>
          </div>

          <div class="container" id="form">
            <div class="row">
              <div class="col text-center">
                <br>
                {% block body_block %}

                {% endblock %}
                <br>
              </div>
            </div>
          </div>

          <!-- Footer -->
          <div class="row">
            <div class="col">
              <hr>
              {% block footer_block %}

              {% endblock %}
            </div>
          </div>

        </div>
      </div>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

RSSapp/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block title_block %}
  RSS feed
{% endblock %}

{% block body_block %}
  <h3>Get the RSS feed for the following sites;</h3>
  <br>

  <form class="text-left" action="{% url 'RSSapp:index' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <label class="mt-3 mb-0">URL {{ forloop.counter }}:</label>{{ field }}
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-danger btn-block" name="button">Get feed</button>
  </form>

{% endblock %}

{% block footer_block %}
  <p class="text-center">Today: {{ date }}</p>
{% endblock %}

RSSapp/templates/results.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block title_block %}
  RSS feed
{% endblock %}

{% block body_block %}
  <h3>RSS feed for the selected sites;</h3>
  <br>
  <div class="text-left">
    {% for feed in feeds %}
      <h4><b>{% cycle titles.0 titles.1 titles.2 %}</b></h4>
      <hr>
      {% if feed.entries|length %}
        <ul>
          {% for post in feed.entries%}
            <li>{{ post.title }}<br>
            <a class="text-danger" href="{{ post.link }}">Read post...</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No RSS feeds found for the given url</p>
      {% endif %}
      <br>
    {% endfor %}
  </div>

{% endblock %}

{% block footer_block %}
  <p class="text-center">Today: {{ date }}</p>
{% endblock %}